import { Product, Category, Review } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cosmic Ocean',
    category: Category.PHOTO,
    price: 15.99,
    imageUrl: 'https://picsum.photos/seed/cosmic/800/600',
    seller: 'Galaxy Snaps',
    description: 'A breathtaking high-resolution digital photo of a nebula, perfect for wallpapers or digital collections.',
    rating: 4.8,
    reviewCount: 152,
  },
  {
    id: 2,
    name: 'Minimalist Oak Frame',
    category: Category.FRAME,
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/frame1/800/600',
    seller: 'FrameWorks',
    description: 'A handcrafted oak wood frame with a minimalist design. Fits 8x10 photos. Shipped ready to hang.',
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: 3,
    name: 'City in Watercolor',
    category: Category.ART,
    price: 250.0,
    imageUrl: 'https://picsum.photos/seed/art1/800/600',
    seller: 'Artistic Visions',
    description: 'An original watercolor painting of a vibrant cityscape at dusk. Comes in a sleek black gallery frame.',
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: 4,
    name: 'Forest Light',
    category: Category.PHOTO,
    price: 12.50,
    imageUrl: 'https://picsum.photos/seed/forest/800/600',
    seller: 'NatureScapes',
    description: 'Sunbeams pierce through a dense forest canopy in this stunning digital photograph.',
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: 5,
    name: 'Geometric Abstraction',
    category: Category.ART,
    price: 180.0,
    imageUrl: 'https://picsum.photos/seed/art2/800/600',
    seller: 'Modern Strokes',
    description: 'A bold and colorful abstract piece featuring geometric shapes. Acrylic on canvas, framed.',
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: 6,
    name: 'Classic Mahogany Frame',
    category: Category.FRAME,
    price: 99.5,
    imageUrl: 'https://picsum.photos/seed/frame2/800/600',
    seller: 'FrameWorks',
    description: 'An elegant mahogany frame with ornate details, perfect for classic portraits. Fits 11x14 photos.',
    rating: 4.8,
    reviewCount: 132,
  },
  {
    id: 7,
    name: 'Mountain Majesty',
    category: Category.PHOTO,
    price: 20.00,
    imageUrl: 'https://picsum.photos/seed/mountain/800/600',
    seller: 'Galaxy Snaps',
    description: 'A crisp, high-detail digital photo of a snow-capped mountain range at sunrise.',
    rating: 4.9,
    reviewCount: 256,
  },
  {
    id: 8,
    name: 'Portrait in Cubism',
    category: Category.ART,
    price: 320.0,
    imageUrl: 'https://picsum.photos/seed/art3/800/600',
    seller: 'Artistic Visions',
    description: 'A modern take on portraiture, inspired by the cubist movement. Framed and signed by the artist.',
    rating: 5.0,
    reviewCount: 23,
  },
  {
    id: 9,
    name: 'Urban Sunset',
    category: Category.PHOTO,
    price: 18.00,
    imageUrl: 'https://picsum.photos/seed/urban/800/600',
    seller: 'NatureScapes',
    description: 'A vibrant sunset over a sprawling cityscape, captured in stunning detail.',
    rating: 4.7,
    reviewCount: 130,
  },
  {
    id: 10,
    name: 'Modern Steel Frame',
    category: Category.FRAME,
    price: 65.00,
    imageUrl: 'https://picsum.photos/seed/frame3/800/600',
    seller: 'FrameWorks',
    description: 'A sleek and modern brushed steel frame. Fits 16x20 prints.',
    rating: 4.6,
    reviewCount: 95,
  },
  {
    id: 11,
    name: 'Abstract Emotions',
    category: Category.ART,
    price: 210.00,
    imageUrl: 'https://picsum.photos/seed/art4/800/600',
    seller: 'Modern Strokes',
    description: 'A powerful abstract piece that explores the spectrum of human emotion through color and texture.',
    rating: 4.8,
    reviewCount: 62,
  },
  {
    id: 12,
    name: 'Serene Beach',
    category: Category.PHOTO,
    price: 14.00,
    imageUrl: 'https://picsum.photos/seed/beach/800/600',
    seller: 'Galaxy Snaps',
    description: 'A tranquil digital photo of waves gently lapping a sandy shore.',
    rating: 4.9,
    reviewCount: 310,
  },
  {
    id: 13,
    name: 'Vintage Ornate Frame',
    category: Category.FRAME,
    price: 120.00,
    imageUrl: 'https://picsum.photos/seed/frame4/800/600',
    seller: 'FrameWorks',
    description: 'An antique-style gold-leafed frame, perfect for adding a touch of classic elegance.',
    rating: 4.9,
    reviewCount: 155,
  },
  {
    id: 14,
    name: 'Digital Dreamscape',
    category: Category.ART,
    price: 195.00,
    imageUrl: 'https://picsum.photos/seed/art5/800/600',
    seller: 'Artistic Visions',
    description: 'A surreal digital painting that blends fantasy and reality. Comes framed and ready to display.',
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 15,
    name: 'Monochrome Cityscape',
    category: Category.PHOTO,
    price: 16.50,
    imageUrl: 'https://picsum.photos/seed/mono/800/600',
    seller: 'NatureScapes',
    description: 'A dramatic black and white photograph of a bustling city street at night.',
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: 16,
    name: 'Rustic Barnwood Frame',
    category: Category.FRAME,
    price: 85.00,
    imageUrl: 'https://picsum.photos/seed/frame5/800/600',
    seller: 'FrameWorks',
    description: 'A charming frame made from reclaimed barnwood, perfect for a rustic decor style.',
    rating: 4.8,
    reviewCount: 140,
  },
  {
    id: 17,
    name: 'Impressionist Garden',
    category: Category.ART,
    price: 280.00,
    imageUrl: 'https://picsum.photos/seed/art6/800/600',
    seller: 'Modern Strokes',
    description: 'An oil painting capturing a flower garden in an impressionistic style, full of vibrant color and light.',
    rating: 4.9,
    reviewCount: 95,
  },
  {
    id: 18,
    name: 'Desert Dunes',
    category: Category.PHOTO,
    price: 19.00,
    imageUrl: 'https://picsum.photos/seed/desert/800/600',
    seller: 'Galaxy Snaps',
    description: 'The shifting sands of a vast desert under the midday sun, captured in high resolution.',
    rating: 4.6,
    reviewCount: 205,
  },
  {
    id: 19,
    name: 'Floating Canvas Frame',
    category: Category.FRAME,
    price: 110.00,
    imageUrl: 'https://picsum.photos/seed/frame6/800/600',
    seller: 'FrameWorks',
    description: 'A modern floating frame designed to make your canvas art appear as if its levitating.',
    rating: 4.7,
    reviewCount: 80,
  },
  {
    id: 20,
    name: 'Surrealist Sculpture',
    category: Category.ART,
    price: 450.00,
    imageUrl: 'https://picsum.photos/seed/art7/800/600',
    seller: 'Artistic Visions',
    description: 'A framed photograph of a mind-bending surrealist sculpture, perfect for modern art lovers.',
    rating: 5.0,
    reviewCount: 42,
  },
  {
    id: 21,
    name: 'Wildlife Portrait',
    category: Category.PHOTO,
    price: 22.00,
    imageUrl: 'https://picsum.photos/seed/wildlife/800/600',
    seller: 'NatureScapes',
    description: 'An intimate, high-detail portrait of a majestic lion.',
    rating: 4.9,
    reviewCount: 350,
  },
  {
    id: 22,
    name: 'Gallery Wall Set',
    category: Category.FRAME,
    price: 250.00,
    imageUrl: 'https://picsum.photos/seed/frame7/800/600',
    seller: 'FrameWorks',
    description: 'A set of seven matching frames in various sizes to create a beautiful gallery wall effortlessly.',
    rating: 4.9,
    reviewCount: 180,
  },
  {
    id: 23,
    name: 'Pop Art Explosion',
    category: Category.ART,
    price: 150.00,
    imageUrl: 'https://picsum.photos/seed/art8/800/600',
    seller: 'Modern Strokes',
    description: 'A vibrant and energetic pop art piece that will be the centerpiece of any room.',
    rating: 4.7,
    reviewCount: 102,
  },
  {
    id: 24,
    name: 'Quiet Lake',
    category: Category.PHOTO,
    price: 13.00,
    imageUrl: 'https://picsum.photos/seed/lake/800/600',
    seller: 'Galaxy Snaps',
    description: 'A serene and calming photo of a mist-covered lake at dawn.',
    rating: 4.8,
    reviewCount: 220,
  },
];

export const MOCK_REVIEWS: Review[] = [
    { id: 1, productId: 1, author: 'Alex R.', rating: 5, comment: 'Absolutely stunning quality! The colors are so vibrant.', date: '2023-10-15' },
    { id: 2, productId: 2, author: 'Samantha B.', rating: 5, comment: 'This frame is perfection. So well-made and looks amazing on my wall.', date: '2023-10-12' },
    { id: 3, productId: 2, author: 'John D.', rating: 4, comment: 'Great quality frame, though it took a little while to ship.', date: '2023-09-28' },
    { id: 4, productId: 3, author: 'Emily C.', rating: 5, comment: 'The artwork is even more beautiful in person. I\'m so happy with this purchase.', date: '2023-10-20' },
    { id: 5, productId: 7, author: 'Chris P.', rating: 5, comment: 'Incredible detail in this photo. Perfect for my new desktop wallpaper. A must-download!', date: '2023-10-18' },
    { id: 6, productId: 4, author: 'Michael T.', rating: 4, comment: 'Beautiful shot, exactly what I was looking for.', date: '2023-09-11' },
];

export const PICKUP_LOCATIONS: string[] = [
    'Dhaka Main Office - Dhanmondi',
    'Chittagong Branch - GEC Circle',
    'Sylhet Hub - Zindabazar',
];